import { AnalysisResults } from '../types'
import { formatTimestamp, formatDuration } from './format'

function downloadFile(content: string, filename: string, type: string): void {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function exportJSON(results: AnalysisResults): void {
  const content = JSON.stringify(results, null, 2)
  downloadFile(content, `analysis_${results.job_id}.json`, 'application/json')
}

export function exportCSV(results: AnalysisResults): void {
  const lines: string[] = []

  // TRANSCRIPT section
  lines.push('TRANSCRIPT')
  lines.push('start_time,end_time,speaker,text,confidence')
  for (const seg of results.transcript) {
    const speaker = seg.speaker ?? ''
    const text = seg.text.replace(/"/g, '""')
    const conf = seg.confidence != null ? seg.confidence.toFixed(4) : ''
    lines.push(`"${formatTimestamp(seg.start_time)}","${formatTimestamp(seg.end_time)}","${speaker}","${text}","${conf}"`)
  }
  lines.push('')

  // FACIAL EXPRESSIONS section
  lines.push('FACIAL EXPRESSIONS')
  lines.push('timestamp,label,confidence,notes')
  for (const ev of results.facial_expressions) {
    const notes = (ev.notes ?? '').replace(/"/g, '""')
    lines.push(`"${formatTimestamp(ev.timestamp)}","${ev.label}","${ev.confidence.toFixed(3)}","${notes}"`)
  }
  lines.push('')

  // INTONATION EVENTS section
  lines.push('INTONATION EVENTS')
  lines.push('timestamp,label,confidence,avg_rms,avg_pitch_hz,pitch_variation,voiced_ratio,notes')
  for (const ev of results.intonation_events) {
    const notes = (ev.notes ?? '').replace(/"/g, '""')
    const f = ev.features
    lines.push(
      `"${formatTimestamp(ev.timestamp)}","${ev.label}","${ev.confidence.toFixed(3)}",` +
      `"${f['avg_rms'] ?? ''}","${f['avg_pitch_hz'] ?? ''}","${f['pitch_variation'] ?? ''}",` +
      `"${f['voiced_ratio'] ?? ''}","${notes}"`
    )
  }

  const content = '\uFEFF' + lines.join('\n') + '\n' // BOM for Excel
  downloadFile(content, `analysis_${results.job_id}.csv`, 'text/csv;charset=utf-8')
}

export function exportMarkdown(results: AnalysisResults): void {
  const lines: string[] = []

  lines.push(`# Analysis Results: ${results.video_filename}`)
  lines.push('')

  if (results.duration != null) {
    lines.push(`**Duration:** ${formatDuration(results.duration)}`)
  }
  lines.push(`**Job ID:** ${results.job_id}`)
  lines.push('')

  // Transcript
  lines.push('## Transcript')
  lines.push('')
  if (results.transcript.length > 0) {
    for (const seg of results.transcript) {
      const speakerPrefix = seg.speaker ? `[${seg.speaker}] ` : ''
      lines.push(`**[${formatTimestamp(seg.start_time)} – ${formatTimestamp(seg.end_time)}]** ${speakerPrefix}${seg.text}`)
      lines.push('')
    }
  } else {
    lines.push('*No transcript available.*')
    lines.push('')
  }

  // Facial expressions
  lines.push('## Facial Expressions')
  lines.push('')
  lines.push('> Observable facial expressions detected by automated analysis — not psychological diagnoses.')
  lines.push('')
  if (results.facial_expressions.length > 0) {
    for (const ev of results.facial_expressions) {
      const noteStr = ev.notes ? ` — ${ev.notes}` : ''
      lines.push(`- **[${formatTimestamp(ev.timestamp)}]** ${ev.label} (${Math.round(ev.confidence * 100)}%)${noteStr}`)
    }
  } else {
    lines.push('*No facial expression events detected.*')
  }
  lines.push('')

  // Intonation
  lines.push('## Intonation / Prosody')
  lines.push('')
  lines.push('> Observable speech characteristics — not conclusions about internal emotional state.')
  lines.push('')
  if (results.intonation_events.length > 0) {
    for (const ev of results.intonation_events) {
      const noteStr = ev.notes ? ` — ${ev.notes}` : ''
      const pitchHz = ev.features['avg_pitch_hz']
      const pitchStr = pitchHz ? `, pitch: ${Math.round(pitchHz)} Hz` : ''
      lines.push(`- **[${formatTimestamp(ev.timestamp)}]** ${ev.label} (${Math.round(ev.confidence * 100)}%${pitchStr})${noteStr}`)
    }
  } else {
    lines.push('*No intonation events detected.*')
  }
  lines.push('')

  // Disclaimer
  lines.push('---')
  lines.push('')
  lines.push('## Disclaimer')
  lines.push('')
  lines.push(
    'This analysis is generated by automated algorithms and is intended as an observational aid ' +
    'for user research purposes only. Facial expression detection is geometric and approximate; ' +
    'it requires a clear frontal view of the participant\'s face. Prosody analysis reflects ' +
    'acoustic features of the speech signal. Neither analysis constitutes a psychological ' +
    'assessment, diagnosis, or definitive characterization of the participant\'s mental state, ' +
    'emotions, or intentions. Researchers should exercise professional judgment when interpreting ' +
    'these results.'
  )
  lines.push('')

  downloadFile(lines.join('\n'), `analysis_${results.job_id}.md`, 'text/markdown')
}
